"""Builds a downloadable Markdown summary of a completed financial analysis."""
from datetime import datetime
from typing import Any, Dict


def build_markdown_report(financial_data: Dict[str, Any], results: Dict[str, Any]) -> str:
    lines = [
        "# Personal Financial Plan",
        f"_Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}_",
        "",
        "## Overview",
        f"- Monthly income: ₹{financial_data.get('monthly_income', 0):,.2f}",
        f"- Dependants: {financial_data.get('dependants', 0)}",
        "",
    ]

    budget = results.get("budget_analysis") or {}
    lines += ["## Budget Analysis", f"Total monthly expenses: **₹{budget.get('total_expenses', 0):,.2f}**", ""]
    if budget.get("spending_categories"):
        lines.append("| Category | Amount | % of spending |")
        lines.append("|---|---|---|")
        for cat in sorted(budget["spending_categories"], key=lambda c: c.get("amount", 0), reverse=True):
            lines.append(f"| {cat['category']} | ₹{cat['amount']:,.2f} | {cat.get('percentage', 0):.1f}% |")
        lines.append("")
    if budget.get("recommendations"):
        lines.append("**Recommendations:**")
        for rec in budget["recommendations"]:
            savings = f" (potential savings: ₹{rec['potential_savings']:,.2f}/mo)" if rec.get("potential_savings") else ""
            lines.append(f"- **{rec['category']}**: {rec['recommendation']}{savings}")
        lines.append("")

    savings = results.get("savings_strategy") or {}
    ef = savings.get("emergency_fund") or {}
    lines += [
        "## Savings Strategy",
        f"Emergency fund target: **₹{ef.get('recommended_amount', 0):,.2f}** "
        f"(currently ₹{ef.get('current_amount', 0):,.2f} - {ef.get('current_status', 'Unknown')})",
        "",
    ]
    if savings.get("recommendations"):
        lines.append("**Allocation recommendations:**")
        for rec in savings["recommendations"]:
            lines.append(f"- **{rec['category']}**: ₹{rec['amount']:,.2f}/month - {rec.get('rationale', '')}")
        lines.append("")
    if savings.get("automation_techniques"):
        lines.append("**Automation techniques:**")
        for tech in savings["automation_techniques"]:
            lines.append(f"- **{tech['name']}**: {tech['description']}")
        lines.append("")

    debt = results.get("debt_reduction") or {}
    lines += ["## Debt Reduction", f"Total debt: **₹{debt.get('total_debt', 0):,.2f}**", ""]
    plans = debt.get("payoff_plans") or {}
    if plans.get("avalanche") and plans.get("snowball"):
        av, sb = plans["avalanche"], plans["snowball"]
        lines.append("| Method | Total interest | Months to payoff |")
        lines.append("|---|---|---|")
        lines.append(f"| Avalanche | ₹{av['total_interest']:,.2f} | {av['months_to_payoff']} |")
        lines.append(f"| Snowball | ₹{sb['total_interest']:,.2f} | {sb['months_to_payoff']} |")
        lines.append("")
    if debt.get("recommendations"):
        lines.append("**Recommendations:**")
        for rec in debt["recommendations"]:
            impact = f" _{rec['impact']}_" if rec.get("impact") else ""
            lines.append(f"- **{rec['title']}**: {rec['description']}{impact}")
        lines.append("")

    goal_plan = results.get("goal_plan") or {}
    if goal_plan.get("goals"):
        lines += [
            "## Financial Goals",
            f"Available monthly surplus for goals: **₹{goal_plan.get('available_monthly_surplus', 0):,.2f}**",
            "",
            "| Goal | Target | Required/mo | Allocated/mo | Projected months | On track |",
            "|---|---|---|---|---|---|",
        ]
        for goal in goal_plan["goals"]:
            lines.append(
                f"| {goal['name']} | ₹{goal['target_amount']:,.2f} | "
                f"₹{goal['required_monthly_contribution']:,.2f} | ₹{goal['monthly_contribution_allocated']:,.2f} | "
                f"{goal['projected_months_to_reach']} | {'Yes' if goal['on_track'] else 'No'} |"
            )
        lines.append("")
        if goal_plan.get("prioritization_summary"):
            lines.append(f"**Prioritization:** {goal_plan['prioritization_summary']}")
            lines.append("")
        if goal_plan.get("recommendations"):
            lines.append("**Recommendations:**")
            for rec in goal_plan["recommendations"]:
                lines.append(f"- {rec}")
            lines.append("")
        if goal_plan.get("tradeoffs"):
            lines.append(f"**Tradeoffs:** {goal_plan['tradeoffs']}")
            lines.append("")

    lines.append("---")
    lines.append("_Generated by AI Financial Coach. This is not professional financial advice._")
    return "\n".join(lines)
